# **Kaggle – DataTops®**
Tu TA ha decidido cambiar de aires y, por eso, ha comprado una tienda de portátiles. Sin embargo, su única especialidad es Data Science, por lo que ha decidido crear un modelo de ML para establecer los mejores precios.

¿Podrías ayudar a tu profe a mejorar ese modelo?

## Aspectos importantes
- Última submission:
    - Mañana: 17 de febrero a las 5pm
    - Tarde: 19 de febrero a las 5pm
- **Enlace de la competición**: https://www.kaggle.com/t/c5cc87b50c4b4770bdc8f5acbe15577d
- **Requisito**: Estar registrado en [Kaggle](https://www.kaggle.com/)

## Métrica:
El error cuadrático medio (RMSE, por sus siglas en inglés) es una medida de la desviación estándar de los residuos (errores de predicción). Los residuos representan la diferencia entre los valores observados y los valores predichos por el modelo. El RMSE indica qué tan dispersos están estos errores: cuanto menor es el RMSE, más cercanas están las predicciones a los valores reales. En otras palabras, el RMSE mide qué tan bien se ajusta la línea de regresión a los datos.


$$ RMSE = \sqrt{\frac{1}{n}\Sigma_{i=1}^{n}{\Big(\frac{d_i -f_i}{\sigma_i}\Big)^2}}$$

## 1. Librerías

In [1]:
import numpy as np
import pandas as pd
from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
import urllib.request

## 2. Datos

In [2]:
# Para que funcione necesitas bajarte los archivos de datos de Kaggle
df = pd.read_csv("./data/train.csv",index_col= "laptop_ID")

### 2.1 Exploración de los datos

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 912 entries, 755 to 229
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           912 non-null    object
 1   Product           912 non-null    object
 2   TypeName          912 non-null    object
 3   Inches            912 non-null    float64
 4   ScreenResolution  912 non-null    object
 5   Cpu               912 non-null    object
 6   Ram               912 non-null    object
 7   Memory            912 non-null    object
 8   Gpu               912 non-null    object
 9   OpSys             912 non-null    object
 10  Weight            912 non-null    object
 11  Price_in_euros    912 non-null    float64
dtypes: float64(2), object(10)
memory usage: 92.6+ KB

In [4]:
df.head()

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_in_euros
laptop_ID,,,,,,,,,,,,
755,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 10,1.86kg,539.00
618,Dell,Inspiron 7559,Gaming,15.6,Full HD 1920x1080,Intel Core i7 6700HQ 2.6GHz,16GB,1TB HDD,Nvidia GeForce GTX 960<U+039C>,Windows 10,2.59kg,879.01
909,HP,ProBook 450,Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,1TB HDD,Nvidia GeForce 930MX,Windows 10,2.04kg,900.00
2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
286,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2.0GHz,4GB,1TB HDD,AMD Radeon R5 M430,Linux,2.25kg,428.00

In [5]:
'''
Antes de continuar debemos hacer una transformacion de los datos para que el modelo permita su correcto funcionamiento. Ahora transformaremos con la siguiente logica:
One-hot encoding(get_dummies) = Cuando la variable no guarde una jerarquia como tal 
Ordinal encoding = Cuando la variable si que guarde una jerarquia
Aplicaremos todo esto a todos los objetos que en la descripcion aparezcan como objects

'''

'\nAntes de continuar debemos hacer una transformacion de los datos para que el modelo permita su correcto funcionamiento. Ahora transformaremos con la siguiente logica:\nOne-hot encoding(get_dummies) = Cuando la variable no guarde una jerarquia como tal \nOrdinal encoding = Cuando la variable si que guarde una jerarquia\nAplicaremos todo esto a todos los objetos que en la descripcion aparezcan como objects\n\n'

In [6]:
ordinal_cols = ["ScreenResolution","Cpu","Ram","Memory","Weight"]
one_hot_cols = ["Company", "Product","TypeName","Gpu","OpSys", "ScreenResolution","Cpu","Ram","Memory","Weight"]

In [7]:
import category_encoders as ce
encoder = ce.TargetEncoder(cols= one_hot_cols)
df[one_hot_cols] = encoder.fit_transform(df[["Company", "Product","TypeName","Gpu","OpSys", "ScreenResolution","Cpu","Ram","Memory","Weight"]], df["Price_in_euros"])

In [8]:
df

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_in_euros
laptop_ID,,,,,,,,,,,,
755,1093.484640,896.754608,766.723674,15.6,1168.386533,553.022980,1181.682765,1224.399362,1070.603692,1161.645951,838.783656,539.00
618,1173.998679,1081.446015,1701.049555,15.6,1168.386533,1510.534268,1938.087425,681.252310,1106.586373,1161.645951,1177.283687,879.01
909,1093.484640,1026.054431,766.723674,15.6,1168.386533,1332.186766,1181.682765,681.252310,1091.328884,1161.645951,983.545937,900.00
2,1294.117288,1099.964056,1552.960384,13.3,1099.450666,1099.964056,1181.682765,1043.903346,1095.488932,1277.758506,1109.403577,898.94
286,1173.998679,812.965790,766.723674,15.6,1168.386533,929.473941,573.200824,681.252310,876.735845,633.995890,1004.834182,428.00
...,...,...,...,...,...,...,...,...,...,...,...,...
28,1173.998679,1049.932354,766.723674,15.6,1168.386533,977.901814,1181.682765,1224.399362,974.064902,1161.645951,693.969087,800.00
1160,1093.484640,1215.979274,1337.084762,13.3,1317.848915,1175.147063,1181.682765,1224.399362,1070.603692,1161.645951,1208.833651,1629.00
78,1053.578417,1012.451308,766.723674,15.6,1168.386533,902.337743,1181.682765,985.760407,1142.610322,641.531917,693.969087,519.00
23,1093.484640,994.346848,766.723674,15.6,524.277870,997.076642,573.200824,627.902845,960.506814,641.531917,838.783656,258.00
229,1173.998679,1594.351818,1701.049555,17.3,1368.960394,1742.461379,1938.087425,1766.188917,1653.728041,1161.645951,1516.935556,2456.34

In [9]:
df.tail()

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_in_euros
laptop_ID,,,,,,,,,,,,
28,1173.998679,1049.932354,766.723674,15.6,1168.386533,977.901814,1181.682765,1224.399362,974.064902,1161.645951,693.969087,800.00
1160,1093.484640,1215.979274,1337.084762,13.3,1317.848915,1175.147063,1181.682765,1224.399362,1070.603692,1161.645951,1208.833651,1629.00
78,1053.578417,1012.451308,766.723674,15.6,1168.386533,902.337743,1181.682765,985.760407,1142.610322,641.531917,693.969087,519.00
23,1093.484640,994.346848,766.723674,15.6,524.277870,997.076642,573.200824,627.902845,960.506814,641.531917,838.783656,258.00
229,1173.998679,1594.351818,1701.049555,17.3,1368.960394,1742.461379,1938.087425,1766.188917,1653.728041,1161.645951,1516.935556,2456.34

In [10]:
df.describe()

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_in_euros
count,912.000000,912.000000,912.000000,912.000000,912.000000,912.000000,912.000000,912.000000,912.000000,912.000000,912.000000,912.000000
mean,1093.152727,1111.780525,1105.932235,14.981579,1062.300220,1135.497977,1102.694602,1101.912200,1105.819671,1110.504883,1046.776350,1111.724090
std,187.338983,131.915701,405.197281,1.436719,310.502754,316.092546,447.230899,402.124469,242.834080,183.261038,188.440593,687.959172
min,609.880132,812.965790,766.723674,10.100000,524.277870,553.022980,573.200824,479.728331,520.560328,633.995890,658.488955,174.000000
25%,1053.578417,1029.401324,766.723674,14.000000,943.961656,902.337743,573.200824,681.252310,1022.754498,1161.645951,970.197702,589.000000
50%,1093.484640,1085.607301,766.723674,15.600000,1168.386533,1085.440319,1181.682765,1224.399362,1123.962420,1161.645951,1080.719985,978.000000
75%,1173.998679,1179.226260,1552.960384,15.600000,1283.295236,1332.186766,1181.682765,1224.399362,1225.131403,1161.645951,1164.636845,1483.942500
max,1620.483224,1594.351818,1701.049555,18.400000,1499.618281,1742.461379,1938.087425,1819.083001,1898.935670,1518.059712,1760.610950,6099.000000

### 2.3 Definir X e y

In [11]:
X = df.drop(['Price_in_euros'], axis=1)
y = df['Price_in_euros'].copy()
X_train = df.drop(['Price_in_euros'], axis=1)
y_train = df['Price_in_euros'].copy()
X.shape

(912, 11)

In [12]:
y.shape

(912,)

### 2.4 Dividir X_train, X_test, y_train, y_test

In [13]:
X_train

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
laptop_ID,,,,,,,,,,,
755,1093.484640,896.754608,766.723674,15.6,1168.386533,553.022980,1181.682765,1224.399362,1070.603692,1161.645951,838.783656
618,1173.998679,1081.446015,1701.049555,15.6,1168.386533,1510.534268,1938.087425,681.252310,1106.586373,1161.645951,1177.283687
909,1093.484640,1026.054431,766.723674,15.6,1168.386533,1332.186766,1181.682765,681.252310,1091.328884,1161.645951,983.545937
2,1294.117288,1099.964056,1552.960384,13.3,1099.450666,1099.964056,1181.682765,1043.903346,1095.488932,1277.758506,1109.403577
286,1173.998679,812.965790,766.723674,15.6,1168.386533,929.473941,573.200824,681.252310,876.735845,633.995890,1004.834182
...,...,...,...,...,...,...,...,...,...,...,...
28,1173.998679,1049.932354,766.723674,15.6,1168.386533,977.901814,1181.682765,1224.399362,974.064902,1161.645951,693.969087
1160,1093.484640,1215.979274,1337.084762,13.3,1317.848915,1175.147063,1181.682765,1224.399362,1070.603692,1161.645951,1208.833651
78,1053.578417,1012.451308,766.723674,15.6,1168.386533,902.337743,1181.682765,985.760407,1142.610322,641.531917,693.969087
23,1093.484640,994.346848,766.723674,15.6,524.277870,997.076642,573.200824,627.902845,960.506814,641.531917,838.783656
229,1173.998679,1594.351818,1701.049555,17.3,1368.960394,1742.461379,1938.087425,1766.188917,1653.728041,1161.645951,1516.935556

In [14]:
y_train

laptop_ID
755      539.00
618      879.01
909      900.00
2        898.94
286      428.00
         ...
28       800.00
1160    1629.00
78       519.00
23       258.00
229     2456.34
Name: Price_in_euros, Length: 912, dtype: float64

## 3. Procesado de datos

Nuestro target es la columna `Price_in_euros`

In [15]:
target = "Price_in_euros"

In [16]:
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor

In [17]:
from sklearn.model_selection import cross_val_score

-----------------------------------------------------------------------------------------------------------------

## 4. Modelado

### 4.1 Baseline de modelos

In [18]:
rf_reg = RandomForestRegressor(max_depth = 10, random_state= 42)
lgb_reg = LGBMRegressor(max_depth = 10, random_state = 42, verbose = -1)
xgb_reg = XGBRegressor(max_depth = 10, random_state = 42)

modelos_reg = {
    "Random Forest": rf_reg,
    "LightGBM": lgb_reg,
    "XGBoost Regressor": xgb_reg
}

### 4.2 Sacar métricas, valorar los modelos

Recuerda que en la competición se va a evaluar con la métrica de ``RMSE``.

In [19]:
for nombre, modelo in zip(["XGBRegressor","LGBMRegressor","RandomForestRegressor"],[xgb_reg, lgb_reg, rf_reg]):
    print(f"Para {nombre}:", end = " ")
    print("neg_mean_absolute error:", np.mean(cross_val_score(modelo, X_train, y_train, cv = 5, scoring = "neg_root_mean_squared_error")))

Para XGBRegressor: neg_mean_absolute error: -206.14028292958474
Para LGBMRegressor: neg_mean_absolute error: -193.9655320861186
Para RandomForestRegressor: neg_mean_absolute error: -189.71355839847115

In [20]:
def objective(trial):
    param_grid = {
        "n_estimators": trial.suggest_int("n_estimators", 100, 800),
        "max_depth": trial.suggest_int("max_depth", 3, 70),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 20),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 10),
        "max_features": trial.suggest_categorical("max_features", ["sqrt", "log2", None]),
        "criterion": trial.suggest_categorical("criterion", ["squared_error", "absolute_error"]),
        "max_samples": trial.suggest_float("max_samples", 0.5, 1.0)
    }

    model = XGBRegressor(**param_grid, random_state=42, n_jobs=-1)

    score = cross_val_score(
        model,
        X_train,
        y_train,
        cv=5,
        scoring="neg_root_mean_squared_error",
        n_jobs=-1
    ).mean()

    return score

In [21]:
import optuna
study = optuna.create_study(direction="maximize", 
                            sampler=optuna.samplers.TPESampler(seed=42))

c:\Users\Dani\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2026-02-18 18:06:42,698] A new study created in memory with name: no-name-5c0ea6d2-ee94-450e-98fc-5be45254bd96

In [22]:
study.optimize(objective, n_trials=50)

[I 2026-02-18 18:06:45,876] Trial 0 finished with value: -204.31431764472254 and parameters: {'n_estimators': 362, 'max_depth': 67, 'min_samples_split': 15, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'criterion': 'squared_error', 'max_samples': 0.8540362888980227}. Best is trial 0 with value: -204.31431764472254.
[I 2026-02-18 18:06:48,602] Trial 1 finished with value: -204.31431764472254 and parameters: {'n_estimators': 114, 'max_depth': 68, 'min_samples_split': 17, 'min_samples_leaf': 3, 'max_features': None, 'criterion': 'squared_error', 'max_samples': 0.645614570099021}. Best is trial 0 with value: -204.31431764472254.
[I 2026-02-18 18:06:50,921] Trial 2 finished with value: -204.57960279831997 and parameters: {'n_estimators': 528, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 'log2', 'criterion': 'absolute_error', 'max_samples': 0.5232252063599989}. Best is trial 0 with value: -204.31431764472254.
[I 2026-02-18 18:06:53,087] Trial 3 finished with value: -203.18327115903347 and parameters: {'n_estimators': 525, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'criterion': 'absolute_error', 'max_samples': 0.7200762468698007}. Best is trial 3 with value: -203.18327115903347.
[I 2026-02-18 18:06:53,798] Trial 4 finished with value: -204.31431764472254 and parameters: {'n_estimators': 185, 'max_depth': 36, 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_features': 'log2', 'criterion': 'absolute_error', 'max_samples': 0.5924272277627636}. Best is trial 3 with value: -203.18327115903347.
[I 2026-02-18 18:06:54,563] Trial 5 finished with value: -204.31431764472254 and parameters: {'n_estimators': 779, 'max_depth': 55, 'min_samples_split': 19, 'min_samples_leaf': 9, 'max_features': 'log2', 'criterion': 'squared_error', 'max_samples': 0.6626651653816322}. Best is trial 3 with value: -203.18327115903347.
[I 2026-02-18 18:06:55,137] Trial 6 finished with value: -204.33370522461883 and parameters: {'n_estimators': 372, 'max_depth': 21, 'min_samples_split': 17, 'min_samples_leaf': 4, 'max_features': 'log2', 'criterion': 'squared_error', 'max_samples': 0.9934434683002586}. Best is trial 3 with value: -203.18327115903347.
[I 2026-02-18 18:06:55,619] Trial 7 finished with value: -204.50367821462504 and parameters: {'n_estimators': 641, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 9, 'max_features': None, 'criterion': 'absolute_error', 'max_samples': 0.5579345297625649}. Best is trial 3 with value: -203.18327115903347.
[I 2026-02-18 18:06:56,306] Trial 8 finished with value: -204.31431764472254 and parameters: {'n_estimators': 705, 'max_depth': 45, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': None, 'criterion': 'absolute_error', 'max_samples': 0.7361074625809747}. Best is trial 3 with value: -203.18327115903347.
[I 2026-02-18 18:06:56,919] Trial 9 finished with value: -204.31431764472254 and parameters: {'n_estimators': 183, 'max_depth': 51, 'min_samples_split': 16, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'criterion': 'squared_error', 'max_samples': 0.5539457134966522}. Best is trial 3 with value: -203.18327115903347.
[I 2026-02-18 18:06:57,023] Trial 10 finished with value: -185.016383932677 and parameters: {'n_estimators': 510, 'max_depth': 3, 'min_samples_split': 11, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'criterion': 'absolute_error', 'max_samples': 0.8299820082607529}. Best is trial 10 with value: -185.016383932677.
[I 2026-02-18 18:06:57,238] Trial 11 finished with value: -190.17813134107016 and parameters: {'n_estimators': 533, 'max_depth': 5, 'min_samples_split': 11, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'criterion': 'absolute_error', 'max_samples': 0.8371806780254722}. Best is trial 10 with value: -185.016383932677.
[I 2026-02-18 18:06:57,371] Trial 12 finished with value: -190.61929025880457 and parameters: {'n_estimators': 464, 'max_depth': 4, 'min_samples_split': 12, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'criterion': 'absolute_error', 'max_samples': 0.8480938523249588}. Best is trial 10 with value: -185.016383932677.
[I 2026-02-18 18:06:58,023] Trial 13 finished with value: -204.3107744604094 and parameters: {'n_estimators': 598, 'max_depth': 29, 'min_samples_split': 11, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'criterion': 'absolute_error', 'max_samples': 0.8559889011067059}. Best is trial 10 with value: -185.016383932677.
[I 2026-02-18 18:06:58,106] Trial 14 finished with value: -183.62692631472152 and parameters: {'n_estimators': 369, 'max_depth': 3, 'min_samples_split': 12, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'criterion': 'absolute_error', 'max_samples': 0.9355732454459806}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:06:58,725] Trial 15 finished with value: -204.3146383304076 and parameters: {'n_estimators': 323, 'max_depth': 25, 'min_samples_split': 8, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'criterion': 'absolute_error', 'max_samples': 0.9729723766826407}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:06:58,879] Trial 16 finished with value: -195.210644375071 and parameters: {'n_estimators': 271, 'max_depth': 6, 'min_samples_split': 14, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'criterion': 'absolute_error', 'max_samples': 0.9271140226318387}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:06:59,539] Trial 17 finished with value: -204.31430747283017 and parameters: {'n_estimators': 423, 'max_depth': 31, 'min_samples_split': 13, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'criterion': 'absolute_error', 'max_samples': 0.9138936297287702}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:06:59,903] Trial 18 finished with value: -205.19785475362178 and parameters: {'n_estimators': 278, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'criterion': 'absolute_error', 'max_samples': 0.7975089991412907}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:00,492] Trial 19 finished with value: -204.33370522461883 and parameters: {'n_estimators': 458, 'max_depth': 21, 'min_samples_split': 10, 'min_samples_leaf': 9, 'max_features': None, 'criterion': 'absolute_error', 'max_samples': 0.9217364950080464}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:01,175] Trial 20 finished with value: -204.31431764472254 and parameters: {'n_estimators': 649, 'max_depth': 43, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'criterion': 'absolute_error', 'max_samples': 0.785356617583685}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:01,298] Trial 21 finished with value: -185.6501213083339 and parameters: {'n_estimators': 555, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'criterion': 'absolute_error', 'max_samples': 0.8093118705991658}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:01,617] Trial 22 finished with value: -203.7256475475802 and parameters: {'n_estimators': 574, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'criterion': 'absolute_error', 'max_samples': 0.7973736500379813}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:02,113] Trial 23 finished with value: -204.20836185173874 and parameters: {'n_estimators': 418, 'max_depth': 18, 'min_samples_split': 13, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'criterion': 'absolute_error', 'max_samples': 0.8865741636152447}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:02,216] Trial 24 finished with value: -184.93867671862017 and parameters: {'n_estimators': 505, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'criterion': 'absolute_error', 'max_samples': 0.9505022299528941}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:02,549] Trial 25 finished with value: -203.7256475475802 and parameters: {'n_estimators': 478, 'max_depth': 9, 'min_samples_split': 12, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'criterion': 'absolute_error', 'max_samples': 0.9603410731497625}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:02,866] Trial 26 finished with value: -203.7256475475802 and parameters: {'n_estimators': 387, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'criterion': 'squared_error', 'max_samples': 0.9470559952075531}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:03,486] Trial 27 finished with value: -204.30113958657893 and parameters: {'n_estimators': 291, 'max_depth': 24, 'min_samples_split': 14, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'criterion': 'absolute_error', 'max_samples': 0.8965821419223567}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:03,590] Trial 28 finished with value: -184.6989373638335 and parameters: {'n_estimators': 485, 'max_depth': 3, 'min_samples_split': 20, 'min_samples_leaf': 9, 'max_features': None, 'criterion': 'absolute_error', 'max_samples': 0.8818093859996249}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:04,240] Trial 29 finished with value: -204.31431764472254 and parameters: {'n_estimators': 373, 'max_depth': 63, 'min_samples_split': 20, 'min_samples_leaf': 10, 'max_features': None, 'criterion': 'squared_error', 'max_samples': 0.8722229525830042}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:04,561] Trial 30 finished with value: -206.14413466064144 and parameters: {'n_estimators': 318, 'max_depth': 10, 'min_samples_split': 18, 'min_samples_leaf': 9, 'max_features': None, 'criterion': 'absolute_error', 'max_samples': 0.9867023758166332}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:04,707] Trial 31 finished with value: -190.7278869421234 and parameters: {'n_estimators': 518, 'max_depth': 4, 'min_samples_split': 15, 'min_samples_leaf': 9, 'max_features': None, 'criterion': 'absolute_error', 'max_samples': 0.9417797413785126}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:04,801] Trial 32 finished with value: -184.84300152999134 and parameters: {'n_estimators': 500, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 8, 'max_features': None, 'criterion': 'absolute_error', 'max_samples': 0.8885218888371754}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:05,090] Trial 33 finished with value: -196.3550849617515 and parameters: {'n_estimators': 425, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 5, 'max_features': None, 'criterion': 'absolute_error', 'max_samples': 0.8925519589066082}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:05,537] Trial 34 finished with value: -205.16213218969227 and parameters: {'n_estimators': 611, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 10, 'max_features': None, 'criterion': 'absolute_error', 'max_samples': 0.7643072609046269}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:05,898] Trial 35 finished with value: -205.19785475362178 and parameters: {'n_estimators': 490, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 6, 'max_features': None, 'criterion': 'absolute_error', 'max_samples': 0.6951110227008407}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:06,448] Trial 36 finished with value: -204.49657818790814 and parameters: {'n_estimators': 685, 'max_depth': 19, 'min_samples_split': 7, 'min_samples_leaf': 7, 'max_features': 'log2', 'criterion': 'squared_error', 'max_samples': 0.9130679123565673}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:06,790] Trial 37 finished with value: -204.57960279831997 and parameters: {'n_estimators': 415, 'max_depth': 12, 'min_samples_split': 20, 'min_samples_leaf': 10, 'max_features': None, 'criterion': 'absolute_error', 'max_samples': 0.9992483437747102}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:06,939] Trial 38 finished with value: -195.18951881088248 and parameters: {'n_estimators': 237, 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 2, 'max_features': 'log2', 'criterion': 'absolute_error', 'max_samples': 0.9625213574147339}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:07,426] Trial 39 finished with value: -204.50367821462504 and parameters: {'n_estimators': 772, 'max_depth': 16, 'min_samples_split': 3, 'min_samples_leaf': 9, 'max_features': None, 'criterion': 'squared_error', 'max_samples': 0.8739154189069618}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:08,047] Trial 40 finished with value: -204.31431764472254 and parameters: {'n_estimators': 351, 'max_depth': 37, 'min_samples_split': 18, 'min_samples_leaf': 9, 'max_features': None, 'criterion': 'absolute_error', 'max_samples': 0.6225658394072078}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:08,152] Trial 41 finished with value: -184.84300152999134 and parameters: {'n_estimators': 500, 'max_depth': 3, 'min_samples_split': 15, 'min_samples_leaf': 8, 'max_features': 'log2', 'criterion': 'absolute_error', 'max_samples': 0.8503043744939472}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:08,266] Trial 42 finished with value: -185.65756649324786 and parameters: {'n_estimators': 557, 'max_depth': 3, 'min_samples_split': 16, 'min_samples_leaf': 8, 'max_features': 'log2', 'criterion': 'absolute_error', 'max_samples': 0.9367320584583734}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:08,607] Trial 43 finished with value: -205.02743887013602 and parameters: {'n_estimators': 497, 'max_depth': 11, 'min_samples_split': 16, 'min_samples_leaf': 7, 'max_features': 'log2', 'criterion': 'absolute_error', 'max_samples': 0.8232743360701555}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:08,907] Trial 44 finished with value: -195.28635053807108 and parameters: {'n_estimators': 458, 'max_depth': 7, 'min_samples_split': 15, 'min_samples_leaf': 8, 'max_features': 'log2', 'criterion': 'absolute_error', 'max_samples': 0.8691037371460615}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:09,215] Trial 45 finished with value: -195.28635053807108 and parameters: {'n_estimators': 536, 'max_depth': 7, 'min_samples_split': 13, 'min_samples_leaf': 9, 'max_features': 'log2', 'criterion': 'absolute_error', 'max_samples': 0.9048179373695262}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:09,328] Trial 46 finished with value: -185.7955572356725 and parameters: {'n_estimators': 576, 'max_depth': 3, 'min_samples_split': 18, 'min_samples_leaf': 4, 'max_features': 'log2', 'criterion': 'absolute_error', 'max_samples': 0.8540360222541977}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:09,981] Trial 47 finished with value: -204.31431764472254 and parameters: {'n_estimators': 395, 'max_depth': 69, 'min_samples_split': 12, 'min_samples_leaf': 8, 'max_features': None, 'criterion': 'squared_error', 'max_samples': 0.9747060880915338}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:10,085] Trial 48 finished with value: -194.79079723412212 and parameters: {'n_estimators': 143, 'max_depth': 6, 'min_samples_split': 19, 'min_samples_leaf': 10, 'max_features': None, 'criterion': 'absolute_error', 'max_samples': 0.7626628476230429}. Best is trial 14 with value: -183.62692631472152.
[I 2026-02-18 18:07:10,433] Trial 49 finished with value: -205.02743887013602 and parameters: {'n_estimators': 442, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 9, 'max_features': 'log2', 'criterion': 'absolute_error', 'max_samples': 0.9469644724419625}. Best is trial 14 with value: -183.62692631472152.

In [23]:
optuna.visualization.plot_param_importances(study)

In [24]:
optuna.visualization.plot_optimization_history(study)

In [25]:
best_params = study.best_params

In [26]:
best_n_estimators = best_params["n_estimators"]
best_max_depth = best_params["max_depth"]
best_min_samples_split = best_params["min_samples_split"]
best_min_samples_leaf = best_params["min_samples_leaf"]
best_max_features = best_params["max_features"]
best_criterion = best_params["criterion"]
best_max_samples = best_params["max_samples"]

In [27]:
best_model = XGBRegressor(
    n_estimators=best_n_estimators,
    max_depth=best_max_depth,
    min_samples_split=best_min_samples_split,
    min_samples_leaf=best_min_samples_leaf,
    max_features=best_max_features,
    criterion=best_criterion,
    max_samples=best_max_samples,
    random_state=42,
    n_jobs=-1
)

In [28]:
best_model.fit(X_train,y_train)

c:\Users\Dani\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\training.py:199: UserWarning:

[18:07:11] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "criterion", "max_features", "max_samples", "min_samples_leaf", "min_samples_split" } are not used.

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, criterion='absolute_error', device=None,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, feature_types=None, feature_weights=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=3, max_features='sqrt',
             max_leaves=None, max_samples=0.9355732454459806,
             min_child_weight=None, min_samples_leaf=8, min_samples_split=12,
             missing=nan, ...)

### 4.3 Optimización (up to you 🫰🏻)

-----------------------------------------------------------------

## Una vez listo el modelo, toca predecir ``test.csv``

**RECUERDA: APLICAR LAS TRANSFORMACIONES QUE HAYAS REALIZADO EN `train.csv` a `test.csv`.**


Véase:
- Estandarización/Normalización
- Eliminación de Outliers
- Eliminación de columnas
- Creación de columnas nuevas
- Gestión de valores nulos
- Y un largo etcétera de técnicas que como Data Scientist hayas considerado las mejores para tu dataset.

## 1. Carga los datos de `test.csv` para predecir.

In [29]:
X_pred = pd.read_csv("./data/test.csv", index_col = "laptop_ID")
X_pred.head()

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
laptop_ID,,,,,,,,,,,
209,Lenovo,Legion Y520-15IKBN,Gaming,15.6,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,512GB SSD,Nvidia GeForce GTX 1060,No OS,2.4kg
1281,Acer,Aspire ES1-531,Notebook,15.6,1366x768,Intel Celeron Dual Core N3060 1.6GHz,4GB,500GB HDD,Intel HD Graphics 400,Linux,2.4kg
1168,Lenovo,V110-15ISK (i3-6006U/4GB/1TB/No,Notebook,15.6,1366x768,Intel Core i3 6006U 2.0GHz,4GB,1TB HDD,Intel HD Graphics 520,No OS,1.9kg
1231,Dell,Inspiron 7579,2 in 1 Convertible,15.6,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,2.191kg
1020,HP,ProBook 640,Notebook,14.0,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,4GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.95kg

In [30]:
X_pred.tail()

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
laptop_ID,,,,,,,,,,,
820,MSI,GE72MVR 7RG,Gaming,17.3,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,512GB SSD + 1TB HDD,Nvidia GeForce GTX 1070,Windows 10,2.9kg
948,Toshiba,Tecra Z40-C-12X,Notebook,14.0,IPS Panel Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.47kg
483,Dell,Precision M5520,Workstation,15.6,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,8GB,256GB SSD,Nvidia Quadro M1200,Windows 10,1.78kg
1017,HP,Probook 440,Notebook,14.0,1366x768,Intel Core i5 7200U 2.5GHz,4GB,500GB HDD,Intel HD Graphics 620,Windows 10,1.64kg
421,Asus,ZenBook Flip,2 in 1 Convertible,13.3,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.27kg

In [31]:
X_pred.info()

<class 'pandas.core.frame.DataFrame'>
Index: 391 entries, 209 to 421
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           391 non-null    object
 1   Product           391 non-null    object
 2   TypeName          391 non-null    object
 3   Inches            391 non-null    float64
 4   ScreenResolution  391 non-null    object
 5   Cpu               391 non-null    object
 6   Ram               391 non-null    object
 7   Memory            391 non-null    object
 8   Gpu               391 non-null    object
 9   OpSys             391 non-null    object
 10  Weight            391 non-null    object
dtypes: float64(1), object(10)
memory usage: 36.7+ KB

 ## 2. Replicar el procesado para ``test.csv``

In [32]:
X_pred

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
laptop_ID,,,,,,,,,,,
209,Lenovo,Legion Y520-15IKBN,Gaming,15.6,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,512GB SSD,Nvidia GeForce GTX 1060,No OS,2.4kg
1281,Acer,Aspire ES1-531,Notebook,15.6,1366x768,Intel Celeron Dual Core N3060 1.6GHz,4GB,500GB HDD,Intel HD Graphics 400,Linux,2.4kg
1168,Lenovo,V110-15ISK (i3-6006U/4GB/1TB/No,Notebook,15.6,1366x768,Intel Core i3 6006U 2.0GHz,4GB,1TB HDD,Intel HD Graphics 520,No OS,1.9kg
1231,Dell,Inspiron 7579,2 in 1 Convertible,15.6,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,2.191kg
1020,HP,ProBook 640,Notebook,14.0,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,4GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.95kg
...,...,...,...,...,...,...,...,...,...,...,...
820,MSI,GE72MVR 7RG,Gaming,17.3,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,512GB SSD + 1TB HDD,Nvidia GeForce GTX 1070,Windows 10,2.9kg
948,Toshiba,Tecra Z40-C-12X,Notebook,14.0,IPS Panel Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.47kg
483,Dell,Precision M5520,Workstation,15.6,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,8GB,256GB SSD,Nvidia Quadro M1200,Windows 10,1.78kg
1017,HP,Probook 440,Notebook,14.0,1366x768,Intel Core i5 7200U 2.5GHz,4GB,500GB HDD,Intel HD Graphics 620,Windows 10,1.64kg
421,Asus,ZenBook Flip,2 in 1 Convertible,13.3,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.27kg

In [33]:
X_pred[one_hot_cols] = encoder.transform(X_pred[one_hot_cols])

In [34]:
X_pred

,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
laptop_ID,,,,,,,,,,,
209,1053.578417,1076.414942,1701.049555,15.6,1168.386533,1742.461379,1938.087425,1819.083001,1653.728041,641.531917,884.587761
1281,609.880132,995.019802,766.723674,15.6,524.277870,604.011346,573.200824,627.902845,520.560328,633.995890,884.587761
1168,1053.578417,1111.724090,766.723674,15.6,524.277870,929.473941,573.200824,681.252310,1070.603692,641.531917,1042.851395
1231,1173.998679,1111.724090,1337.084762,15.6,1175.119678,902.337743,1181.682765,1224.399362,1142.610322,1161.645951,1111.724090
1020,1093.484640,1104.197910,766.723674,14.0,1168.386533,902.337743,573.200824,1224.399362,1142.610322,1161.645951,1282.943032
...,...,...,...,...,...,...,...,...,...,...,...
820,1620.483224,1231.069459,1701.049555,17.3,1168.386533,1742.461379,1938.087425,1456.465259,1898.935670,1161.645951,1268.883895
948,1243.951857,1111.724090,766.723674,14.0,1368.960394,1085.440319,573.200824,714.437637,1070.603692,1161.645951,1113.110813
483,1173.998679,1111.724090,1672.825045,15.6,1168.386533,1742.461379,1181.682765,1224.399362,1295.335363,1161.645951,1111.724090
1017,1093.484640,1085.607301,766.723674,14.0,524.277870,902.337743,573.200824,627.902845,1142.610322,1161.645951,1105.652964
421,1068.685818,1143.689530,1337.084762,13.3,1175.119678,902.337743,1181.682765,1224.399362,1142.610322,1161.645951,1271.403086

In [35]:
predictions_submit = best_model.predict(X_pred)
predictions_submit

array([1369.1355 ,  273.55753,  755.7109 ,  981.28094,  988.3595 ,
        827.0373 , 1070.7388 ,  877.0437 , 1033.911  ,  979.09314,
       1219.7153 , 1924.1322 ,  905.5639 , 1342.789  ,  973.56726,
        988.1421 , 1434.1158 , 1297.2649 , 1801.5103 ,  643.9036 ,
       1505.1993 , 1016.6183 ,  877.09174, 1108.8268 ,  457.44217,
        708.5711 ,  936.04517, 1109.4972 , 3028.1262 , 1059.0636 ,
       1305.5856 ,  418.21683,  850.30383, 3296.9775 , 1311.6945 ,
       1139.4491 ,  647.82056, 1213.0134 ,  865.8817 , 1691.176  ,
        859.8629 ,  734.81433,  530.1698 , 1139.6819 , 1199.1866 ,
       1213.6136 , 1167.2675 ,  629.6721 ,  562.0112 ,  358.41962,
       1352.0566 ,  673.94385, 1107.8113 ,  451.78903, 1892.8158 ,
       1947.2926 , 1025.497  , 1063.6649 ,  709.1747 ,  939.60004,
       1839.4458 , 2017.2295 ,  815.5244 , 2135.902  , 1804.5444 ,
       1132.6383 , 1163.8589 , 1005.1263 , 2258.9211 , 1660.1747 ,
        898.3565 , 1036.7646 ,  972.7255 , 1855.935  , 1141.2247 ,
       1443.6013 , 1453.2557 , 1838.1055 , 1610.0503 , 1065.3416 ,
        772.45483, 1222.6816 , 1823.4521 , 1209.0243 , 1197.0847 ,
       1263.3934 ,  901.3188 , 1065.2603 ,  883.1188 , 1167.3206 ,
        922.57086, 1253.2504 ,  796.87427, 1478.6554 , 1365.549  ,
       1254.2948 ,  782.55383,  966.66736,  934.5029 ,  883.1818 ,
       1327.106  ,  795.2996 , 1422.4407 , 1000.10394,  797.3656 ,
       1170.4324 , 1555.1602 ,  507.19858,  362.7787 , 1119.7699 ,
       1934.9965 ,  797.03345,  940.2935 ,  592.4767 ,  979.0103 ,
        622.9428 ,  630.88086, 1696.305  ,  818.94635,  953.37177,
        736.7953 ,  749.94763, 1173.581  , 1241.8201 , 1655.9768 ,
        794.93146, 2011.7913 , 1089.7861 ,  882.7384 , 1021.54614,
       1653.6141 , 1092.4547 , 1076.3706 , 1201.5288 ,  984.0736 ,
       1444.9204 , 1099.0704 ,  977.4216 , 1153.6956 ,  466.1392 ,
       1176.2919 ,  692.2511 , 1260.7953 , 1212.0902 , 1891.0514 ,
        953.37177, 1104.0876 ,  968.87305, 1468.015  ,  699.2915 ,
        705.691  ,  831.7021 ,  875.0203 ,  869.7841 ,  663.5036 ,
        897.55255, 1134.1791 ,  991.0298 ,  569.44586,  356.23788,
        433.30862, 2035.4698 , 1189.8826 ,  663.9672 , 1211.2512 ,
       1023.71234, 1773.1896 ,  217.62692,  768.62646,  756.0994 ,
       1169.6335 ,  429.924  ,  926.6535 ,  561.4874 , 2057.398  ,
        640.6665 , 1106.3732 ,  489.09924, 1055.8942 , 1027.4457 ,
        861.7111 , 5682.325  , 1181.2249 , 1046.096  , 1000.15546,
       1984.8363 , 1038.818  ,  964.78217, 1490.695  ,  868.673  ,
        981.8913 , 1027.538  ,  447.89166, 1016.71405,  761.1643 ,
        869.60803, 1258.9075 , 1038.5615 ,  672.02106,  285.95575,
       1173.581  , 1195.8318 ,  874.7226 ,  624.07   ,  574.2899 ,
        529.31635, 1167.5155 ,  325.15546, 1298.8654 ,  340.45544,
        972.5649 , 1131.6993 ,  993.3327 , 1124.4875 ,  467.73492,
       1445.6653 , 1288.5002 , 1007.64   ,  554.58624,  485.95035,
        815.00946, 1182.2147 ,  823.79156, 1229.4901 , 1021.64154,
       1111.4323 ,  839.0059 , 1100.0187 , 1038.0537 ,  813.9437 ,
        957.3163 ,  433.7273 , 1030.9667 , 1075.1581 ,  827.60205,
        747.4261 , 2270.4814 ,  928.7621 , 1056.4126 , 1742.5934 ,
       1107.1516 ,  567.78644, 1054.2396 , 1288.23   , 1033.9655 ,
       2347.634  , 1005.89233, 1040.4017 ,  679.2582 , 1193.1635 ,
       1136.3992 ,  925.4102 , 1193.831  , 1080.8053 , 1193.831  ,
       2887.478  ,  818.02716,  801.2786 , 1518.5697 , 1002.9158 ,
        868.6776 ,  924.6315 ,  900.7323 ,  853.5554 , 2076.8142 ,
       2233.575  , 1087.343  ,  541.0818 , 1265.9994 , 1344.923  ,
        498.22635,  472.6525 , 1282.0422 , 1463.7855 , 1101.259  ,
        752.9937 ,  470.3721 ,  763.09216, 1358.4117 ,  938.0261 ,
        585.1409 , 1261.4005 , 1197.9141 ,  867.7373 ,  979.2161 ,
       1051.5419 , 1256.3785 , 1589.8037 , 3288.1572 ,  437.40222,
       1008.71704, 1271.2194 , 1089.6632 , 1579.6759 ,  719.611  ,
       1094.0162 , 1099.1586 ,  850.1144 , 2447.3696 ,  782.6868 ,
       1852.3119 ,  426.61502,  960.6396 ,  852.0765 ,  692.17255,
       1510.4249 , 1727.9016 ,  785.55646, 1823.7614 , 1440.8594 ,
        417.16025, 1103.5992 , 1000.28644,  459.42938,  883.2625 ,
       1155.0964 , 2663.3726 , 1043.983  , 1301.597  ,  861.0429 ,
       1534.644  , 1021.7941 , 1139.5392 , 1200.5214 , 1070.8634 ,
       1343.4822 , 1355.816  ,  934.47644,  501.4919 , 2933.1465 ,
        420.00815, 1087.2411 , 1603.9111 ,  961.7762 ,  424.8094 ,
        852.5207 ,  461.83765,  437.40222, 1664.8607 ,  986.9843 ,
        944.86194,  933.97864, 1346.8804 , 1210.6317 , 1107.1516 ,
        889.3765 ,  422.0483 , 1391.4072 ,  869.2472 ,  659.80804,
       1024.9897 , 1016.447  ,  676.5566 ,  899.3439 , 1025.4585 ,
        303.82553, 1213.5405 ,  923.98975, 1541.7013 , 1204.6567 ,
        578.43945,  688.32025,  945.34393,  897.2629 , 1168.845  ,
        964.5816 , 1823.8033 , 1574.9487 ,  777.5991 , 1767.6526 ,
       1845.8829 , 1262.3441 ,  539.9724 , 1094.6289 , 1187.7628 ,
       1288.8142 ,  583.34674, 1037.1782 ,  619.43677,  985.3425 ,
        460.5576 , 1118.4125 , 1183.1178 ,  305.20828, 2040.4347 ,
       1049.4689 , 2165.9177 , 1117.9192 , 1226.2166 ,  845.0324 ,
       1421.7659 ], dtype=float32)

**¡OJO! ¿Por qué me da error?**

IMPORTANTE:

- SI EL ARRAY CON EL QUE HICISTEIS `.fit()` ERA DE 4 COLUMNAS, PARA `.predict()` DEBEN SER LAS MISMAS
- SI AL ARRAY CON EL QUE HICISTEIS `.fit()` LO NORMALIZASTEIS, PARA `.predict()` DEBÉIS NORMALIZARLO
- TODO IGUAL SALVO **BORRAR FILAS**, EL NÚMERO DE ROWS SE DEBE MANTENER EN ESTE SET, PUES LA PREDICCIÓN DEBE TENER **391 FILAS**, SI O SI

**Entonces, si al cargar los datos de ``train.csv`` usaste `index_col=0`, ¿tendré que hacer lo también para el `test.csv`?**

In [36]:
# ¿Qué opináis?
# ¿Sí, no?

![wow.jpeg](attachment:wow.jpeg)

## 3. **¿Qué es lo que subirás a Kaggle?**

**Para subir a Kaggle la predicción esta tendrá que tener una forma específica.**

En este caso, la **MISMA** forma que `sample_submission.csv`.

In [37]:
sample = pd.read_csv("data/sample_submission.csv")

In [38]:
sample.head()

   laptop_ID  Price_in_euros
0        209          1949.1
1       1281           805.0
2       1168          1101.0
3       1231          1293.8
4       1020          1832.6

In [39]:
sample.shape

(391, 2)

## 4. Mete tus predicciones en un dataframe llamado ``submission``.

In [40]:
#¿Cómo creamos la submission?
submission = pd.DataFrame({"laptop_ID": X_pred.index , "Price_in_euros" : predictions_submit})

In [41]:
submission.head()

   laptop_ID  Price_in_euros
0        209     1369.135498
1       1281      273.557526
2       1168      755.710876
3       1231      981.280945
4       1020      988.359497

In [42]:
submission.shape

(391, 2)

## 5. Pásale el CHEQUEADOR para comprobar que efectivamente está listo para subir a Kaggle.

In [43]:
def chequeador(df_to_submit):
    """
    Esta función se asegura de que tu submission tenga la forma requerida por Kaggle.

    Si es así, se guardará el dataframe en un `csv` y estará listo para subir a Kaggle.

    Si no, LEE EL MENSAJE Y HAZLE CASO.

    Si aún no:
    - apaga tu ordenador,
    - date una vuelta,
    - enciendelo otra vez,
    - abre este notebook y
    - leelo todo de nuevo.
    Todos nos merecemos una segunda oportunidad. También tú.
    """
    if df_to_submit.shape == sample.shape:
        if df_to_submit.columns.all() == sample.columns.all():
            if df_to_submit.laptop_ID.all() == sample.laptop_ID.all():
                print("You're ready to submit!")
                df_to_submit.to_csv("submission.csv", index = False) #muy importante el index = False
                urllib.request.urlretrieve("https://www.mihaileric.com/static/evaluation-meme-e0a350f278a36346e6d46b139b1d0da0-ed51e.jpg", "gfg.png")
                img = Image.open("gfg.png")
                img.show()
            else:
                print("Check the ids and try again")
        else:
            print("Check the names of the columns and try again")
    else:
        print("Check the number of rows and/or columns and try again")
        print("\nMensaje secreto del TA: No me puedo creer que después de todo este notebook hayas hecho algún cambio en las filas de `test.csv`. Lloro.")

In [44]:
chequeador(submission)

You're ready to submit!

In [50]:
y_test = X_pred[target]

KeyError: 'Price_in_euros'

In [51]:
from sklearn.metrics import mean_squared_error
y_pred = best_model.predict(X_pred)
print(round(mean_squared_error(y_test, y_pred),4))

NameError: name 'y_test' is not defined